[plugins]
cloud-buildLogic-spotless = { id = "org.incendo.cloud-build-logic.spotless", version.ref = "cloud-build-logic" }
cloud-buildLogic-rootProject-publishing = { id = "org.incendo.cloud-build-logic.publishing.root-project", version.ref = "cloud-build-logic" }
cloud-buildLogic-rootProject-spotless = { id = "org.incendo.cloud-build-logic.spotless.root-project", version.ref = "cloud-build-logic" }

[versions]
cloud-build-logic = "0.0.13"
ktlint = "1.0.1"
checkstyle = "10.12.5"

# Kotlin
kotlin = "1.9.22"
dokka = "1.9.10"
coroutines = "1.7.3"

# Cloud
cloud = "2.0.0-beta.2"
cloud-minecraft = "2.0.0-beta.3"

# External
immutables = "2.10.1"

# Test
jupiterEngine = "5.10.2"
mockitoCore = "4.11.0"
mockitoJupiter = "4.11.0"
truth = "1.4.1"

[libraries]
cloud-build-logic = { module = "org.incendo:cloud-build-logic", version.ref = "cloud-build-logic" }
gradleKotlinJvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }

# Cloud
cloud-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud" }
cloud-minecraft-extras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloud-minecraft" }

# External
immutables = { group = "org.immutables", name = "value", version.ref = "immutables" }

# Test
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiterEngine" }
jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiterEngine" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockitoJupiter" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
